apiVersion: v1
kind: Service
metadata:
  name: cd-service
  namespace: argocd
spec:
  selector:
    app: cd-argo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  